### ISSUE TITLE
Remove $list_id parameter from mailchimp_ecommerce_update_store()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#1]
See commit: https://github.com/thinkshout/mailchimp-api-php/commit/03e1d6a2607845ed37ce449fc4a9916702b75e64

**Comment by taz77** [comment]
You are up really late/early!

**Comment by ruscoe** [comment]
Somewhere between late and early :)

Thanks for the fix!
