### ISSUE TITLE
Add order functions to mailchimp_ecommerce

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#11]
- mailchimp_ecommerce_add_order()
- mailchimp_ecommerce_update_order()

**Comment by taz77** [comment]
I've start working on this today. First I did the product variant stuff.

**Comment by Greg-Boggs** [comment]
@taz77 so we don't end up stepping on each other, we've started using the "assignees" functionality on Github so that you know what dan and I are actively working on.

**Comment by taz77** [comment]
@Greg-Boggs Yeah, I see you guys have been a lot busier lately than the last month! I will look at how we can deconflict. I have been working on this because I need it by 21 July (contract ends with current ESP).

**Comment by Greg-Boggs** [comment]
We appreciate all your help, especially your expertise around rules and commerce because that's goop to me. We will certainly have things working by July 21.
