### ISSUE TITLE
Implement product hooks in mailchimp_ecommerce_commerce

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#12]
Products in MailChimp require at least one product variant. See: http://developer.mailchimp.com/documentation/mailchimp/guides/getting-started-with-ecommerce/#products
### Map Drupal Commerce "products" to MailChimp "product variants".
- [x] Create product
  hook_commerce_product_insert()
  Create default variant if this is a new product
- [x] Create product variant
  hook_commerce_product_insert()
- [x] Update product variant
  hook_commerce_product_update()
- [x] Delete product variant
  hook_commerce_product_delete()
- [x] Delete product
  hook_commerce_product_delete()
- [x] Delete product automatically if all variants are removed
- [x] Sync existing products with MailChimp when a new store is created via the MailChimp eCommerce admin page

**Comment by taz77** [comment]
Part of this is dependant upon this https://github.com/thinkshout/mailchimp-api-php/issues/15

You should see a PR from me today for the product variant stuff on the API.

**Comment by ruscoe** [comment]
Perfect. Thanks!

**Comment by taz77** [comment]
PR submitted.
