### ISSUE TITLE
Push commits to Drupal.org

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#131]
Commits in the 8.x branch need to be synchronized to Drupal.org so composer can be used to pull the latest dev code.

**Comment by ruscoe** [comment]
Done for now. We'll try to be better about keeping up with this.

**Comment by taz77** [comment]
@ruscoe I have a shell alias I use for committing Drupal projects because I do the same thing (Github+D.O). One alias to push to both remotes.

**Comment by taz77** [comment]
`alias pushdo='git push drupal ; git push bitbucket ; git push github'`

**Comment by ruscoe** [comment]
Nice! Thank you, I'll make use of that.
