### ISSUE TITLE
Fatal error: Declaration of Drupal\...\MailchimpEcommerceCommerceAdminSettings::create(...) must be compatible with Drupal\...\ContainerInjectionInterface::create(...)

### ISSUE THREAD

**Issue by jtphelan** [thinkshout/mailchimp_ecommerce#134]
When I attempt to install the latest code from 8.x-1.x branch and attempt to install I get this error.

`PHP Fatal error:  Declaration of Drupal\mailchimp_ecommerce_commerce\Form\MailchimpEcommerceCommerceAdminSettings::create(Drupal\mailchimp_ecommerce_commerce\Form\ContainerInterface $container) must be compatible with Drupal\Core\DependencyInjection\ContainerInjectionInterface::create(Symfony\Component\DependencyInjection\ContainerInterface $container) in /var/www/html/labstrong/public_html/web/modules/contrib/mailchimp_ecommerce/modules/mailchimp_ecommerce_commerce/src/Form/MailchimpEcommerceCommerceAdminSettings.php on line 9`

It does enable but when I got to the mailchimp settings page I receive this error.

`The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\Routing\Exception\RouteNotFoundException</em>: Route &quot;mailchimp_ecommerce.admin_settings&quot; does not exist. in <em class="placeholder">Drupal\Core\Routing\RouteProvider-&gt;getRouteByName()</em> (line <em class="placeholder">202</em> of <em class="placeholder">core/lib/Drupal/Core/Routing/RouteProvider.php</em>).`

**Comment by jtphelan** [comment]
Server running PHP 7.1
Drupal core: 8.5.3
Commerce: 8.x-2.7
Mailchimp: 8.x-1.6
Mailchimp Ecommerce: 8.x-1.x (From Github)
Mailchimp PHP library: 2.0.0

**Comment by marthinal** [comment]
Created a PR that should fix the issue

**Comment by ruscoe** [comment]
Thank you
