### ISSUE TITLE
Implement cart hooks in mailchimp_ecommerce_commerce

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#14]
A cart is any order that hasn't been completed.

- [ ] Create cart: hook_commerce_order_insert()
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

- [ ] Update cart: hook_commerce_order_update()
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

- [ ] Delete cart: hook_commerce_order_delete()
  - [x] D7 ecommerce
  - [ ] D8 ecommerce
  - [x] D7 ubercart
  - [ ] D8 ubercart

- [x] Delete cart via API after order is complete.
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [x] D7 ubercart
  - [ ] D8 ubercart

**Comment by mshaver** [comment]
I'm moving this to "Done", let me know @ruscoe if that is incorrect.

**Comment by mshaver** [comment]
@ruscoe want to verify this is complete in all 4 versions!

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051115
