### ISSUE TITLE
400: Invalid Resource in the checkout

### ISSUE THREAD

**Issue by marthinal** [thinkshout/mailchimp_ecommerce#140]
This is the error:

`400: Invalid Resource - The resource submitted could not be validated. For field-specific details, see the 'errors' array. a:1:{i:0;O:8:"stdClass":2:{s:5:"field";s:16:"customer.company";s:7:"message";s:43:"Schema describes string, NULL found instead";}}`

We need to remove fields if the value is NULL. See CustomerHandler::buildCustomer().

**Comment by ruscoe** [comment]
Thank you
