### ISSUE TITLE
$description parameter is missing when updating a product

### ISSUE THREAD

**Issue by aaronbowwwls** [thinkshout/mailchimp_ecommerce#146]
A couple dblog messages when updating an order (ubercart). 

> Warning: Missing argument 7 for mailchimp_ecommerce_update_product(), called in ... mailchimp_ecommerce/modules/mailchimp_ecommerce_ubercart/mailchimp_ecommerce_ubercart.module on line 124 and defined in mailchimp_ecommerce_update_product() (line 1027 of ... mailchimp_ecommerce/mailchimp_ecommerce.module).

> Notice: Undefined variable: price in mailchimp_ecommerce_update_product() (line 1042 of ... mailchimp_ecommerce/mailchimp_ecommerce.module).

`mailchimp_ecommerce_update_product(  
    $product['id'],  
    $product['variant_id'],  
    $product['title'],  
    $product['sku'],  
    $product['url'],  
    $product['price']  
  );`

`function mailchimp_ecommerce_update_product($product_id, $product_variant_id, $title, $description = '', $sku, $url, $price, $image_url = '', $stock = 1)`

**Comment by ruscoe** [comment]
Thank you for the pull request. I've merged it in.
