### ISSUE TITLE
Provide rules in mailchimp_ecommerce_commerce

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#16]
Provide a set of rules that could be used for non-standard shopping cart setups.

**Comment by taz77** [comment]
You could assign this task to me if you put me on as a contributor. I maintain Commerce Rules Extra so I have a lot of rules experience.

**Comment by mshaver** [comment]
Hi @taz77, feel free to work on this and open a PR with your changes. We'd be happy to review and merge in, as we were not likely to get to any special rules for non-standard cart setups anyway. Thanks

**Comment by taz77** [comment]
Rules exist now.
