### ISSUE TITLE
Multivalue Stores

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#19]
Currently we make 1 store per website. Mailchimp allows 1 store per list per currency. So, ideally we'd have 1 store per product per currency in Drupal.

**Comment by taz77** [comment]
Within a store, a product can have a different currency than the store.

**Comment by Greg-Boggs** [comment]
That's great news. Can a product also have a different list than the store?

**Comment by taz77** [comment]
Its seems I told you wrong.

I swore that currency was part of the call to make a product. But it isn't. So what I said is false.

http://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/products/

**Comment by mortenson** [comment]
Closing as outdated.
