### ISSUE TITLE
Ensure using the product SKU as the ID of product variants is a sensible approach

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#20]
https://github.com/thinkshout/mailchimp_ecommerce/blob/7.x-1.x/mailchimp_ecommerce.module#L228-L230

This approach would be a problem only if a store owner were to change the SKU of a product. Product variants can share the ID of the parent if necessary.

Variant docs: http://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/products/variants

It might be a better approach to require a `$variant_product_id` parameter for add / update / delete functions in the `mailchimp_ecommerce` module and just provide the SKU as `$variant_product_id` from the `mailchimp_ecommerce_commerce` module.

**Comment by taz77** [comment]
I agree with you on the approach. `mailchimp_ecommerce` is trying to be agnostic of the shopping cart, so the variant ID should be required. If you are using Drupal Commerce, just use the SKU since every variant of a product in Commerce has to have a separate SKU.

**Comment by ruscoe** [comment]
That seems like the best solution. Thanks for confirming that approach makes sense.
