### ISSUE TITLE
Implement base functions to control variants via API

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#22]

**Comment by ruscoe** [comment]
We may already have this (unless there's more):

https://github.com/thinkshout/mailchimp_ecommerce/blob/7.x-1.x/mailchimp_ecommerce.module#L196-L398

**Comment by taz77** [comment]
I am slow this week.... I created the issue then started finding the code you referenced above. It was late and needed sleep. I am +9 hours from you guys :-D
