### ISSUE TITLE
Use UID for customer ID

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#24]
Currently, we use profile ID which means each customer gets 2 id (billing and shipping) and each order from the same person gets 2 new IDs. Instead, we will use UID for ucstomer ID so every person has one customer_id even if they have 5 different orders.

**Comment by ruscoe** [comment]
Fixed in https://github.com/thinkshout/mailchimp_ecommerce/commit/64dde4609817245f76e53abf1726e2269b6b6b81
