### ISSUE TITLE
Edit Customer/ Edit Cart

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#27]
You can only call Add on new items For existing items, you must call Edit. So, before we call addCustomer, AddCart, we have to ensure that the customer or cart doesn't already exist. If it does exist, we need to call edit for that customer or cart.

**Comment by Greg-Boggs** [comment]
Edit customer is now complete.

**Comment by mshaver** [comment]
I'm moving this to "Done", let me know @Greg-Boggs  if that is incorrect.

**Comment by taz77** [comment]
I think this can be closed.
