### ISSUE TITLE
local function names should be safely name spaced

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#28]
Because of the way Drupal 7 scans for hooks, to avoid name space collisions, all local, non hook functions should be preceded with an _ in the function name. Gabe can understand the problem with not doing it and the other way to avoid it.

**Comment by mshaver** [comment]
What is the status of this issue @Greg-Boggs?

**Comment by mortenson** [comment]
Closing as outdated.
