### ISSUE TITLE
Call to undefined eCommerce library function: getCampaign()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#30]
https://github.com/thinkshout/mailchimp_ecommerce/blob/7.x-1.x/mailchimp_ecommerce.module#L709

**Comment by Greg-Boggs** [comment]
It should be defined because I called the Campaign Library just above this code.

**Comment by ruscoe** [comment]
Ah, it's because the variable is named `$mc_ecommerce` but it references the `MailchimpCampaigns` library. The type hinting here confused PHPStorm: https://github.com/thinkshout/mailchimp_ecommerce/blob/7.x-1.x/mailchimp_ecommerce.module#L703

**Comment by ruscoe** [comment]
Fixed: https://github.com/thinkshout/mailchimp_ecommerce/commit/bcecee5370ae20c4378a85833d2c3215fdc692f4
