### ISSUE TITLE
On checkout module is attempting to delete a cart

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#34]
On checkout the module is attempting to delete a cart and returns a 404

Here is the information from my Drupal logs. I am digging into what chain of events that causes this. I see the error on my order confirmation page with Drupal Commerce.

> TYPE    mailchimp_ecommerce
> SEVERITY    error
> FUNCTION    mailchimp_ecommerce_log_error_message
> FILE    /vhost/swingsurgeon/htdocs/sites/all/modules/contrib/mailchimp_ecommerce/mailchimp_ecommerce.module
> LINE    316
> COUNT   1
> DATE    USER    LOCATION    REFERRER    HOSTNAME    MESSAGE OPERATIONS
> 09/04/2016 - 17:07  Brady   payment review  91.67.145.166   Unable to delete a cart: 404: Resource Not Found - The requested resource could not be found.

**Comment by amydecat** [comment]
I was able to complete a cart checkout and did not receive a 404 error. Is there, perhaps, anything unusual about your implementation of Drupal Commerce that might cause the checkout to complete more than once? Interested in learning more and seeing what we can dig up, @taz77!

**Comment by taz77** [comment]
I am going to retest this locally. I have a very complicated cart as we deliver digital media. There are somewhere around 30 different rules that could run at order completion depending on what the customer purchases. There could be something causing the hooks to run twice. Let me investigate further.  BTW, the site is https://www.swingsurgeon.com/shop

**Comment by Greg-Boggs** [comment]
If you use PHP Storm, you can set it to break on exception and then see what's going on in the Drupal stack that triggered the exception.

**Comment by taz77** [comment]
Yes I am using PHPStorm. For some reason I haven't got it to break on exception yet.

**Comment by Greg-Boggs** [comment]
You have to add a PHP breakpoint for "Exception" under view breakpoints in the run menu. I used this extensively when debugging strange results.

**Comment by taz77** [comment]
Closing this issue as I cannot replicate it anymore

**Comment by taz77** [comment]
I spoke to too soon. I been away for several months and I tried to install this module and I am still getting this same error, except the line number has changed to 316. Error is the same `Unable to delete a cart: 404: Resource Not Found - The requested resource could not be found.`

**Comment by taz77** [comment]
This is coming from this function:
```
/**
 * Deletes a cart in the current MailChimp store.
 *
 * @param string $cart_id
 *   The cart ID.
 */
function mailchimp_ecommerce_delete_cart($cart_id) {
  try {
    $store_id = mailchimp_ecommerce_get_store_id();
    if (empty($store_id)) {
      throw new Exception('Cannot delete a cart without a store ID.');
    }

    /* @var \Mailchimp\MailchimpEcommerce $mc_ecommerce */
    $mc_ecommerce = mailchimp_get_api_object('MailchimpEcommerce');
    $mc_ecommerce->deleteCart($store_id, $cart_id);
  }
  catch (Exception $e) {
    mailchimp_ecommerce_log_error_message('Unable to delete a cart: ' . $e->getMessage());
    drupal_set_message($e->getMessage(), 'error');
  }
}
```

**Comment by taz77** [comment]
I see this got fixed finally. I wasn't hallucinating after all :-D https://www.drupal.org/node/2841570
