### ISSUE TITLE
Implement mailchimp_ecommerce_delete_customer()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#37]
- [ ] D7 ecommerce
  - [ ] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

**Comment by mshaver** [comment]
What is the status of this issue @ruscoe?

**Comment by mshaver** [comment]
Consider for GDPR or not at all?

**Comment by mortenson** [comment]
@mshaver I'm closing this as outdated since there wasn't a lot of information to go on here, but if you think this is still a useful feature please open a Drupal.org issue with the information required to action the ticket. Thanks!
