### ISSUE TITLE
Cart and Customer Information Is Incorrect for the API

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#44]
Duplicated from D.O

Installed the module and created a new store on a test list. Running through functional testing. I found that if a user does not exist in your MailChimp list the module will throw an error in messages to the user. A 400 error is shown to the user when the module attempts to create a cart. The error is because the user does not exist which is expected.

Steps to recreate:
1) Install Module, connect to Mailchimp
2) Create a user in Drupal with an email address that does not appear in the connected list/store in Mailchimp
3) In a clean browser, login as the newly created user
4) Go to product on Drupal and add to cart.

The function mailchimp_ecommerce_validate_customer() is not providing an exit to the try/catch to avoid throwing an error.

The specific error is:
`400: Invalid Resource - The resource submitted could not be validated. For field-specific details, see the 'errors' array. a:2:{i:0;O:8:"stdClass":2:{s:5:"field";s:22:"customer.email_address";s:7:"message";s:50:"An email address is required to create a customer.";}i:1;O:8:"stdClass":2:{s:5:"field";s:22:"customer.opt_in_status";s:7:"message";s:50:"An opt-in status is required to create a customer.";}}`

**Comment by taz77** [comment]
The Mailchimp API documentation doesn't say the opt-in status and email address are required, but they are.

I am working a fix right now.

**Comment by taz77** [comment]
See work here. https://github.com/taz77/mailchimp_ecommerce/tree/cart-customer-information-api-correction

**Comment by taz77** [comment]
I have cleared the errors, but no orders are being submitted.

**Comment by taz77** [comment]
PR is good to fix this issue. May last statement resolved itself. For some reason the hook did not execute and the batch job to import products never happened. Cannot replicate that either.

**Comment by ruscoe** [comment]
Merged in. Looks good, thank you.
