### ISSUE TITLE
Don't save store configuration in Drupal if store creation fails in MailChimp

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#49]
If store creation fails in MailChimp for any reason, the `mailchimp_ecommerce_list_id` variable is still set. This removes the MailChimp list selector from the store creation form and is confusing for the user.

Only set `mailchimp_ecommerce_list_id` if the store was successfully created in MailChimp.

**Comment by mshaver** [comment]
Related to #57

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051112
