### ISSUE TITLE
Where to report issues?

### ISSUE THREAD

**Issue by ameenross** [thinkshout/mailchimp_ecommerce#50]
Since this project has a home here on GitHub as well (including issues), what's the preferred channel for issue reports?

**Comment by Greg-Boggs** [comment]
You're welcome to report issues in either Github or Drupal because both email us when people post.

**Comment by ameenross** [comment]
I've reported a bug almost a month ago on [d.o](https://www.drupal.org/node/2853261) and so far have not had a response.

**Comment by taz77** [comment]
I commented on your issue. The fields will be easy to change. Not sure about the profiles. I found there is a lack of documentation on the Commerce API's. I found an outstanding issues and bumped it to critical to add more documentation to the Commerce API.

**Comment by ameenross** [comment]
There's nothing specifically "Commerce API" about that, except the reference fields (which are basically the same as entityreference). The point is that a site builder *could* create a customer profile, where the field on the order that references the profile entity is called `field_my_customer_profile`.

The customer profile reference field used ought to be configurable (Rules module comes to mind), as well as the customer profile's addressfield.

And the `addressfield` fields vary as well. Depending on configuration, you might not even have first/last name fields, but instead have a unified field.

These cases either need to be covered, or the module must check whether the customer profile has compatible configuration, or, as a last resort, it needs to be documented how to configure the addressfield to be compatible.
