### ISSUE TITLE
Second cart appearing in MailChimp, customer API endpoint is cart ID

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#51]
Very strange. Happens every time when adding a new cart. When the cart is removed by ID, both records are removed. Could be a bug in the API playground.

![screen shot 2017-05-23 at 10 43 46 am](https://cloud.githubusercontent.com/assets/87952/26367863/e632a6e6-3fa4-11e7-9114-b5878497394c.png)

**Comment by ruscoe** [comment]
This also propagates to orders.

![screen shot 2017-05-23 at 11 41 55 am](https://cloud.githubusercontent.com/assets/87952/26370505/de4444dc-3fac-11e7-9b3a-985a7ad3a128.png)

**Comment by mshaver** [comment]
Talk to MC about this

**Comment by firewaller** [comment]
This seems to be happening because the module uses the billing profile ID as the customer ID rather than the user ID. A new billing profile is created PER order, therefore multiple carts are created for a single user. I'll create an issue on d.o and link it here.
