### ISSUE TITLE
Error: Call to a member function getStore() on null 

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#53]
An edge case, if you try to setup mailchimp before commerce, you get this 500 error:

 Error: Call to a member function getStore() on null

**Comment by mshaver** [comment]
Potential enhancement

**Comment by mshaver** [comment]
Add is enabled to mailchimp_ecommerce for either Ubercart or Drupal Commerce. Hide admin tab if not.

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051113
