### ISSUE TITLE
 Error message 400: Duplicate Line Item ID - A line item with the provided ID already exists.

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#55]
Click add to cart on a product.
Click add to cart on the same product a second time. 

commerce combines the line items into 1 which makes MC unhappy.

**Comment by ruscoe** [comment]
I've been trying to reproduce this / trick it into happening, but I can't cause the error. Is it still happening with the latest on 8.x-1.x?

**Comment by Greg-Boggs** [comment]
looks fixed to me

**Comment by Greg-Boggs** [comment]
it's back.

**Comment by torgospizza** [comment]
Is this a D7 or D8 issue? In D7 Commerce I'm able to add multiple quantities of one line item without any issue (at least with the latest -dev).
