### ISSUE TITLE
validate a store when enabling it

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#57]
When I create a store, we should check if it exists. If it exists, we should validate customer 1 in the drupal database against mailchimp. If they don't match up, we should prevent the store from being reused and tell the developer to create a new store, or to recover their local database.

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051112
