### ISSUE TITLE
Allow signup during checkout

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#59]
I don't believe it's possible to add fields to the checkout pane in D8. So, we're going to need a code solution. Perhaps a form alter, or custom pane plugin.

**Comment by mshaver** [comment]
Waiting for responses to Drupal Commerce questions about this. Proposed solution: build custom commerce pane to be placed in checkout workflow.

**Comment by benedikt-buchert** [comment]
I think a custom pane is the right solution.
https://docs.drupalcommerce.org/commerce2/developer-guide/checkout/create-custom-checkout-pane

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If this is still a desirable feature, please file a Drupal.org issue with a patch. Thanks!
