### ISSUE TITLE
Adding a product before syncing

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#62]
If you add a product before syncing it, the checkout has a fatal error.

**Comment by ruscoe** [comment]
@Greg-Boggs Do you think it's better to sync the missing product silently in the background when added to a cart, or just not sync any cart line items that don't have a corresponding product in MailChimp?

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051111
