### ISSUE TITLE
Update cart fails with 404

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#63]
It fails because we haven't sent the cart to MC yet!

404: Resource Not Found - The requested resource could not be found.

**Comment by ruscoe** [comment]
We just need to avoid reporting the 404 as an error. It's reasonable for a cart line to not exist when Drupal tries to update it, given the checkout flow. The correct quantity will be sent to MailChimp when the line item is created.

[Committed here](https://github.com/thinkshout/mailchimp_ecommerce/commit/05bf3f1fe387b7867ce1929be2e6f2147de3d3dc).
