### ISSUE TITLE
Backport new product sync process from D8 module [6 hrs]

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#65]
See:

https://github.com/thinkshout/mailchimp_ecommerce/blob/8.x-1.x/modules/mailchimp_ecommerce_commerce/src/Form/MailchimpEcommerceCommerceSync.php

**Comment by ruscoe** [comment]
Committed to 7.x-1.x

**Comment by Greg-Boggs** [comment]
this looks complete...
