### ISSUE TITLE
Order Notification

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#70]
## Overview
To let mailchimp handle order notifications, we have to sync 2 status fields. Please see the mailchimp documentation of these fields, because the Drupal values need to be converted to specific strings.

Fields to add are fulfillment_status,  and financial_status

- [ ] D7 Commerce
- [ ] D7 Ubercart
- [ ] D8 Commerce
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
@mshaver I'm closing this as moving all commerce emails to Mailchimp should be its own issue, once we decide to pursue that feature and they sign off on it.
