### ISSUE TITLE
PHP Fatal error:  Cannot declare class Drupal\mailchimp_ecommerce_ubercart\Form\MailchimpEcommerceUbercartAdminSettings

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#72]
`PHP Fatal error:  Cannot declare class Drupal\mailchimp_ecommerce_ubercart\Form\MailchimpEcommerceUbercartAdminSettings, because the name is already in use in /mailchimp_ecommerce/modules/mailchimp_ecommerce_commerce/src/Form/MailchimpEcommerceCommerceAdminSettings.php on line 31`

**Comment by Greg-Boggs** [comment]
nnnooo :) 👍

**Comment by ruscoe** [comment]
https://github.com/thinkshout/mailchimp_ecommerce/commit/5e2e73b1deaf82a46641c8be9d48b58abee88a7e

Got it :)
