### ISSUE TITLE
Produce Recommendations: Product URL

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#75]
## Overview
Sync the product URL and variant URL to be used for product recommendations. 

- [x] D7 Drupal Commerce
- [x] D8 Drupal Commerce
- [x] D7 Ubercart
- [x] D8 Ubercart

## QA
- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by ruscoe** [comment]
https://github.com/thinkshout/mailchimp_ecommerce/tree/7.x-1.x-recommendations

https://github.com/thinkshout/mailchimp_ecommerce/tree/8.x-1.x-recommendations

**Comment by Greg-Boggs** [comment]
This is done for D8 Commerce.
