### ISSUE TITLE
Landing Site URL: Sync landing_site url 

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#77]
## Overview
The `landing_site` url is used to identify where users ended up after clicking a link in an email newsletter. This value should be synced back to Mailchimp. 

https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/orders/

- [x] D7 Drupal Commerce
- [x] D8 Drupal Commerce
- [x] D7 Ubercart
- [x] D8 Ubercart

**Comment by torgospizza** [comment]
Looking at how MC are [handling this](https://github.com/mailchimp/mc-magento/issues/123) for their Magento integration, they point out that it
> will need to be stored in the user’s session and applied to the API call at time of sending the order over.

and

> If you are looking for a specific param to identify if it came from mailchimp, the utm_source param should begin with "mailchimp" and then have a "-[list unique id]" after it. So looking for that param and if it starts with mailchimp, it is us. Please hand us the full url still.

That probably means an implementation of hook_init() to set the cookie, and then an addition to the `_build_order()` callback to add this value to the order. 

I also think we should delete the cookie when an order is completed, to avoid having a false positive in future orders from that customer.

It might also be a good idea to use the `mailchimp_ecommerce_store_domain` as a default for this value, especially when submitting historical orders. Reason being: the `landing_site` value is a requirement for sending order notifications, but if we enable this module on a site with active shopping carts, those values will not exist. That could mean - for shop owners wanting to use MailChimp's new [Order Notifications automation](https://kb.mailchimp.com/automation/create-order-notifications) - there could potentially be a disruption if the store admin disables regular emails in favor of the MailChimp emails. The worst case scenario would just be "no email gets sent" but that's probably worth avoiding if possible.
