### ISSUE TITLE
Fulfillment Status: Sync fulfillment_status to MC

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#78]
## Overview
The `fulfillment_status` value should be synced back to Mailchimp. This will require an additional contrib module most likely, so we may need a way of requiring if a user wants to enable product recommendations with fulfillment status enabled. 

https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/orders/

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mshaver** [comment]
Related issue: https://www.drupal.org/project/mailchimp_ecommerce/issues/2982728

**Comment by mortenson** [comment]
I believe that issue is where this work should land.
