### ISSUE TITLE
Facebook/Instagram Ad campaigns

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#79]
## Overview
This issue may need more context, but at this point I believe this is related to the following API: `outreach`.

**Comment by mshaver** [comment]
@ruscoe, let's estimate this task first.

**Comment by Greg-Boggs** [comment]
Hrm, Can we update this ticket with a bit more info when we get a chance? Skipping for now.

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051110
