### ISSUE TITLE
Dependant issues on Drupal.org

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp_ecommerce#8]
I got some dependent issue/patches on Drupal.org against the main MailChimp module that I need to get some traction on so I can continue to develop this module. I have band-aid's in place via composer but it would be nice to get the commits on Drupal.org so I can run everything via Drush.

The issue/patch in question is specifically the optional use of Composer for D7

https://www.drupal.org/node/2726765

**Comment by Greg-Boggs** [comment]
Fix pushed to the dev release of 7.x-4.x on D.O.
