### ISSUE TITLE
MC.js

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#80]
## Overview
MailChimp has a new js file that controls many of the api and experience processes between a site and MC. We should look at integrating this new js file in a way that automatically inserts it for a site and puts the correct codes in place. All opt in and configuration for the functionality is done in MailChimp, so most of what we need setup initially is just the mc.js file properly place on the pages. 

## Dev [20 hrs]

Includes both D7 and D8. See subtasks for hours breakdown.

**Comment by ruscoe** [comment]
Documentation: https://docs.google.com/document/d/126d81dXZ3GEGeCHg8b9m3DbXdlet-5sW0A50iobNRes/

Connected sites must be registered with MailChimp: https://us10.admin.mailchimp.com/account/connected-sites/wizard

Use ngrok to get an external URL for a local dev site. MailChimp need to connect to your local site.

JS code is generated by MailChimp. Example:

```js
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/8f6db7bbdc993cd30ee409856/12f71443bba57f7afb4dd056a.js");</script>
```

Once connected, add a pop-up signup form to your local site via the Connected Sites page:
https://us10.admin.mailchimp.com/account/connected-sites/

Users will need a way to paste this code into an admin form and have it inserted into pages via the MailChimp eCommerce module.

![screen shot 2017-11-07 at 11 16 54 am](https://user-images.githubusercontent.com/87952/32512922-68d688e2-c3ad-11e7-8bb4-9621f6f00d7e.png)

**Comment by mshaver** [comment]
@ruscoe, one thing to consider is that the same mc.js file will likely be used for non-ecommerce functionality like newsletter signups and potentially other core MailChimp features. I just want to make sure we're not getting too narrow with it's integration. 

Also, is there a way of pulling the generated js code automatically from MailChimp after you've connected to your account?

**Comment by ruscoe** [comment]
@mshaver Good to know, thank you.

I'm not sure if there's a way for us to pull down the JS code yet, but I would say it's likely we could just generate it if we can get the ID that's being added to the JS URL. I'll experiment with it.

**Comment by ruscoe** [comment]
@mshaver It does look like we can get the embedded JS code without asking the user for it. It's the "connected_site" property when retrieving store information from MailChimp:

http://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/#read-get_ecommerce_stores_store_id

**Comment by mshaver** [comment]
Closing this as I believe connected sites are enabled across modules.
