### ISSUE TITLE
Promo Codes: Add select list option for promo code mergevar

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#85]
MailChimp defines promo codes as a mergevar on a list.

Add a new select field to this form `/admin/config/services/mailchimp/ecommerce` such that, when a list has been selected, the select field is populated with all possible mergevars. The user should select the mergevar that will contain promo codes for that list.

This should be a form alter from within the `mailchimp_ecommerce_promo_code` module.

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051109
