### ISSUE TITLE
Promo Codes: Create mailchimp_ecommerce_promo_code submodule

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#86]
Create a new submodule named `mailchimp_ecommerce_promo_code` that will be used to house all promo code-specific functionality.

Include `commerce_discount` and `commerce_coupon` modules as dependencies.

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051109
