### ISSUE TITLE
Promo Codes: Add a hook that will intercept lists as they are updated from MailChimp

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#88]
Add a new hook to the `mailchimp_lists` module.

Name hook `mailchimp_get_list` with one parameter, so it is invoked as follows:

`module_invoke_all('mailchimp_get_list', $list);`

This hook will allow us to create promo codes in Drupal when a list's mergevars are updated from MailChimp.

Document the hook in the `mailchimp.api.php` file.

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051109
