### ISSUE TITLE
Promo Codes: Create new coupon code if a list contains a promo code mergevar

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#89]
Use the hook defined by #88 to create a new coupon in Drupal.

See `commerce_coupon_form_submit()` for an example.

- [ ] D7 Drupal Commerce
- [ ] D8 Drupal Commerce
- [ ] D7 Ubercart
- [ ] D8 Ubercart

**Comment by mortenson** [comment]
See https://www.drupal.org/project/mailchimp_ecommerce/issues/3051109
