### ISSUE TITLE
Product Recommendations: Inventory

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#90]
## Overview

- [x] D8 Commerce
- [x] D7 Commerce
- [ ] D8 Ubercart
- [ ] D7 Ubercart

#### When stock management is in use

- [x] Enable modules
  - `commerce_stock`
  - `commerce_ss`
  - `commerce_stock_ui`
- [x] Enable stock management for a product type: `/admin/commerce/config/stock/ss`
- [x] Create or edit an existing product and set a stock amount
- [x] Modify functions:
  - `mailchimp_ecommerce_add_product()`
  - `mailchimp_ecommerce_update_product()`
  - Accept an additional argument named `$stock` 
- [x] Modify functions:
  - `mailchimp_ecommerce_add_product()`
  - `mailchimp_ecommerce_update_product()`
  - Update each product variant to contain a new parameter, `inventory_quantity`, which contains the stock value.
- [x] Modify functions:
  - `mailchimp_ecommerce_commerce_commerce_product_insert()` 
  - `mailchimp_ecommerce_commerce_commerce_product_update`
  - Pass the value of `$product->commerce_stock` to:
    - `mailchimp_ecommerce_add_product()`
    - `mailchimp_ecommerce_update_product()`

#### When stock management is not in use

- [x] Modify function `mailchimp_ecommerce_admin_settings()` to make these changes to the MailChimp eCommerce admin form
  - [x] Add a checkbox field named `use_fixed_inventory`
  - [x] Add a textfield named `fixed_inventory_amount` (validate that submitted values are only integers)
  - [x] Store the above two values using `variable_set()`
- [x] Modify functions `mailchimp_ecommerce_add_product()` and `mailchimp_ecommerce_update_product()` so that the product variant property `inventory_quantity` (created earlier in this ticket) is set to the value of `fixed_inventory_amount` only if `use_fixed_inventory` evaluates to true.

It's probably best to allow the user to choose whether or not they want to use a fixed inventory amount than base that decision on whether or not we detect a stock management module. We don't know if the user has written their own module for that purpose or not.

### D8

The maintainers of the `commerce_stock` do not have a D8 release and do not recommend their existing D8 code be used in production.

For D8, it might be best to only provide the option of a fixed inventory amount and not attempt to integrate the unfinished `commerce_stock` module.

The estimate includes this option, but this is open for debate.

## Ubercart

**Complete Drupal Commerce work first as this work depends on some of those changes.**

#### When stock management is in use

- [ ] Enable `uc_stock` module
- [ ] Modify functions:
  - `mailchimp_ecommerce_ubercart_node_insert()`
  - `mailchimp_ecommerce_ubercart_node_update()`
  - `mailchimp_ecommerce_ubercart_batch_add_product()`
  - [ ] Get the stock level of a product by passing the value of `$product['sku']` to function `uc_stock_level()`
  - [ ] Pass the stock level to function `mailchimp_ecommerce_add_product()` function

#### When stock management is not in use

Work already completed as part of Drupal Commerce tasks above.

#### When stock management is in use

- [ ] Enable `uc_stock` module
- [ ] Modify `ProductHandler::addProduct()` to accept an additional argument named `$stock`
- [ ] Modify `BatchSyncProducts::syncProducts()` to pass stock value for each product using function `uc_stock_level()`
- [ ] Modify functions:
  - `mailchimp_ecommerce_ubercart_node_insert()`
  - `mailchimp_ecommerce_ubercart_node_update()`
  - Pass stock value for product to `ProductHandler:: addProduct()` and `ProductHandler::updateProduct()` using function `uc_stock_level()`

#### When stock management is not in use

Same as D7, but add fields to: `MailchimpEcommerceAdminSettings::buildForm()`

**Comment by ruscoe** [comment]
@mshaver Added steps for Ubercart and updated estimate.

**Comment by mshaver** [comment]
Notes: 
* Currently defaulting to 100 for D7 ubercart & D8 ubercart and commerce.  
   * `producthandler class` 
* Adapt D7 commerce code for ubercart, then port to D8 versions.

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp_ecommerce/issues/3051108
