### ISSUE TITLE
Embed MailChimp JavaScript in page

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#92]
# D7

## Dev [6 hrs]

- [x] Use `hook_page_alter` to add the following JavaScript code to every page:

```
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script"," $CONNECTED_SITE_URL ");</script>
```
- [x] Replace `$CONNECTED_SITE_URL` in the code above with the value of the variable added in #91 

# D8

## Dev [6 hrs]

- [ ] Use `hook_page_top` to add the following JavaScript code to every page:

```
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script"," $CONNECTED_SITE_URL ");</script>
```
- [ ] Replace $CONNECTED_SITE_URL in the code above with the value of the variable added in #91 

`hook_page_top` expects a render array, so use a simple `#markup` render array to insert the JavaScript.

**Comment by mshaver** [comment]
I'm moving this to "Done", let me know @ruscoe if that is incorrect. Are there still some D8 items?
