### ISSUE TITLE
Product Fields

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#94]
For products do we need to fill in:

* **visibility:** possibly published value?
* **backorders:** related to inventory, which we're not really handling
* **images:** we will be doing this in #76  
* **published_at_foriegn:** it seems like this is just the published date, not sure why it's called "foriegn" 
* **handle:** no idea 
* **type:** category if one exists for the product 
* **vendor:** is there anything in commerce or ubercart that describes manufacture or something like that?

**Comment by mshaver** [comment]
@Greg-Boggs, I've included a few questions here as follow up. Want to clarify those and then I'll send to MailChimp for follow up?

**Comment by mortenson** [comment]
Closing as outdated.
